### ISSUE TITLE
"." command not properly inserting autoclosed quotes

### ISSUE THREAD

**Issue by sergeichestakov** [replit/codemirror-vim#87] opened 2023-02-28 23:00 UTC
When you hit the "." command to repeat the last action or edit in normal mode, the subsequent insert does not properly insert closing quotes or braces that are auto-inserted.

See demo below:

![cm-vim-period-bug](https://user-images.githubusercontent.com/24947334/222001226-334ddeda-7686-4035-be02-9a78837830ff.gif)

**Comment by nightwing** [comment] 2023-03-02 21:40
closing as duplicate of https://github.com/replit/codemirror-vim/issues/65, will make a pull request with fix in next few days

**Closed by nightwing** 2023-03-02 21:40 UTC
